steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install', '--max-old-space-size=4096']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy']

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHMEM_8'
