steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-app-image', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/my-app-image']

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'my-app-service',
      '--image', 'gcr.io/$PROJECT_ID/my-app-image',
      '--platform', 'managed',
      '--region', 'us-central1',
      '--allow-unauthenticated',
      '--port', '9000'
    ]

images:
  - 'gcr.io/$PROJECT_ID/my-app-image'

logsBucket: 'gs://mi-nuevo-bucket-de-logs'
