steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-app-image', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['run', '-d', '-p', '8080:8080', 'gcr.io/$PROJECT_ID/my-app-image']
images:
- 'gcr.io/$PROJECT_ID/my-app-image'
logsBucket: 'gs://mi-nuevo-bucket-de-logs'
