steps:
- name: 'gcr.io/cloud-builders/npm'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      npm install -g n && \
      n 18.17.0 && \
      npm install -g npm@latest && \
      npm install
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy']

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
logsBucket: 'gs://mi-nuevo-bucket-de-logs'
