steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
  env:
  - 'NODE_OPTIONS=--max_old_space_size=4096'
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy']

options:
  logging: CLOUD_LOGGING_ONLY
